# Generated by Django 4.0.2 on 2022-02-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_seed_feeding_bird_seeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='color',
        ),
    ]
